# Generated by Django 4.2 on 2023-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temporary_categories',
            field=models.ManyToManyField(related_name='temporary_posts', to='news.category'),
        ),
    ]
